site_name: PGMQ
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: light mode
nav:
  - PGMQ: 'index.md'
  - API:
    - SQL:
      - 'api/sql/types.md'
      - 'api/sql/functions.md'
  - FIFO Queues: 'fifo-queues.md'
  - Partitioned Queues: 'partitioned-queues.md'
  - Topic Routing: 'topics.md'
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- codehilite:
- admonition
- extra
- pymdownx.snippets:
    check_paths: true
plugins:
  - search
  - mkdocstrings
extra:
  version:
    provider: mike
